import { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "../styles/base.scss";

const roboto_mono = Roboto_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "NeNetFlix",
    description: "Generated by some guy from internet",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={roboto_mono.className}>{children}</body>
        </html>
    );
}
