import { Metadata } from "next";
import "../styles/base.scss";
import localFont from "next/font/local";

const myFont = localFont({
    src: "../../public/fonts/NetflixSans_W_Rg.woff2",
    display: "swap",
});

export const metadata: Metadata = {
    title: "NeNetFlix",
    description: "Generated by some guy from internet",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={myFont.className}>{children}</body>
        </html>
    );
}
