import Link from "next/link";
import s from "../index.module.scss";
import { AuthMethods } from "@/components/AuthMethods";

import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Sign up",
    description: "Generated by some guy from internet",
};

export default function SignUp() {
    return (
        <section className={s.auth}>
            <div className={s.authForm}>
                <h1 className={s.signIn}>Регистрация</h1>

                <form className={s.inputContainer}>
                    <input
                        type="text"
                        name="email"
                        placeholder="Ваш Email"
                        className={s.input}
                        maxLength={255}
                        required
                    />

                    <button className={s.submitBtn} type="submit">
                        Зарегестрироваться
                    </button>
                </form>
                <p className={s.signUpText}>
                    Уже есть аккаунт?
                    <Link href="/login">Войти</Link>
                </p>
                <AuthMethods />
            </div>
        </section>
    );
}
